name: CI - Branch

on: push
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-pr:
    runs-on: ubuntu-latest
    outputs:
      exists_pr: ${{ steps.pr.outputs.exists }}
    steps:
      - name: Check PR
        id: pr
        uses: sogoagain/check-opened-pr-action@v0.1
  build:
    needs: check-pr
    if: needs.check-pr.outputs.exists_pr == 'false'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Test
        run: ./gradlew test

      - name: Build
        run: ./gradlew buildFatJar
